# Generated by Django 5.1.4 on 2025-01-12 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefrigeratorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor1_temp', models.FloatField()),
                ('sensor2_temp', models.FloatField()),
                ('is_out_of_range', models.BooleanField()),
                ('event_date', models.DateTimeField()),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_records', to='fr1.fridge')),
            ],
        ),
    ]
