# Generated by Django 5.1.4 on 2025-01-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fridges/'),
        ),
    ]
