# Generated by Django 5.1.4 on 2025-01-14 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fr1", "0002_fridge_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refrigeratordata",
            name="event_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
