# Generated by Django 5.1.5 on 2025-01-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fr1", "0003_alter_refrigeratordata_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refrigeratordata",
            name="event_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
